use huskytech;
INSERT INTO merchandiseType (brand, model, price) VALUES
("Dell", "XPS 15", 1200),
("Dell", "XPS 13", 1000),
("Apple", "MacBook Air", 1200),
("Apple", "MacBook Pro", 1500),
("Samsung", "Galaxy Book", 1200),
("Google", "Pixelbook Go", 1200),
("Lenovo", "X1 Carbon Gen 8", 950),
("Lenovo", "X1 Carbon Gen 7", 1000),
("Alienware", "Alienware m15 R3", 1500),
("Alienware", "Alienware Area-51m r2", 1800),
("Apple", "IPhone X", 400),
("Apple", "IPhone 11", 500),
("Apple", "IPhone 8", 300),
("Samsung", "Galaxy Note 7", 500),  
("Google", "Google Pixel 5", 700),
("Google", "Google Pixel 4", 500),
("Nokia", "Nokia 3V", 300),
("Nokia", "Nokia 6.2", 400),
("HTC", "HTC U11", 500),
("HTC", "HTC 12", 600),
("Dell", "Inspiron 24 5000", 1200),
("Dell", "Inspiron 27 7000", 1500),
("Dell", "OptiPlex 7780", 1400),
("Lenovo", "IdeaCentre A540", 1000),
("Lenovo", "Yoga A940", 2300),
("Microsoft", "Surface Studio 2", 3500),
("Apple", "iMac", 1100),
("Apple", "Mac mini", 900),
("HP", "HP EliteOne 800", 1300),
("HP", "HP Z2 Mini G4", 800);

INSERT INTO Laptop (brand, model, ram, processor) VALUES
("Dell", "XPS 15", 16, "10th Generation Intel Core i7"),
("Dell", "XPS 13", 32, "11th Generation Intel Core i9"),
("Apple", "MacBook Air", 32, "10th Generation Intel Core i9"),
("Apple", "MacBook Pro", 32, "11th Generation Intel Core i9"),
("Samsung", "Galaxy Book", 16, "10th Generation Intel Core i7"),
("Google", "Pixelbook Go", 8, "11th Generation Intel Core i7"),
("Lenovo", "X1 Carbon Gen 8", 16, "11th Generation Intel Core i7"),
("Lenovo", "X1 Carbon Gen 7", 32, "10th Generation Intel Core i9"),
("Alienware", "Alienware m15 R3", 32, "10th Generation Intel Core i9"),
("Alienware", "Alienware Area-51m r2", 16, "11th Generation Intel Core i9");


INSERT INTO Phone (brand, model, operateSys, space) VALUES
("Apple", "IPhone X", "IOS 14", 128),
("Apple", "IPhone 11", "IOS 13", 64),
("Apple", "IPhone 8", "IOS 14", 32),
("Samsung", "Galaxy Note 7", "Android 10", 64),  
("Google", "Google Pixel 5", "Android 8", 32),
("Google", "Google Pixel 4", "Android 10", 64),
("Nokia", "Nokia 3V", "Symbianv2", 16),
("Nokia", "Nokia 6.2", "Symbianv3", 8),
("HTC", "HTC U11", "Android 7.1", 64),
("HTC", "HTC 12", "Android 9", 128);


INSERT INTO Desktop VALUES
("Dell", "Inspiron 24 5000", "10th Generation Intel Core i7", 16),
("Dell", "Inspiron 27 7000", "11th Generation Intel Core i9", 32),
("Dell", "OptiPlex 7780", "10th Generation Intel Core i9", 8),
("Lenovo", "IdeaCentre A540", "11th Generation Intel Core i9", 32),
("Lenovo", "Yoga A940", "10th Generation Intel Core i7", 16),
("Microsoft", "Surface Studio 2", "11th Generation Intel Core i7", 16),
("Apple", "iMac",  "10th Generation Intel Core i9", 32),
("Apple", "Mac mini",  "10th Generation Intel Core i9", 32),
("HP", "HP EliteOne 800", "11th Generation Intel Core i9", 16),
("HP", "HP Z2 Mini G4", "11th Generation Intel Core i7", 16);

INSERT INTO Color (brand, model, color) VALUES
("Apple", "IPhone X", "Gold"),
("Apple", "IPhone 11", "Black"),
("Apple", "IPhone 8", "White"),
("Samsung", "Galaxy Note 7", "Silver"),  
("Google", "Google Pixel 5", "Gold"),
("Google", "Google Pixel 4", "Black"),
("Nokia", "Nokia 3V", "Black"),
("Nokia", "Nokia 6.2", "White"),
("HTC", "HTC U11", "Silver"),
("HTC", "HTC 12", "Blue");

INSERT INTO Carrier (brand, model, carrier) VALUES
("Apple", "IPhone X", "Verizon"),
("Apple", "IPhone 11", "AT&T"),
("Apple", "IPhone 8", "T-Mobile"),
("Samsung", "Galaxy Note 7", "Verizon"),  
("Google", "Google Pixel 5", "AT&T"),
("Google", "Google Pixel 4", "Verizon"),
("Nokia", "Nokia 3V", "Verizon"),
("Nokia", "Nokia 6.2", "AT&T"),
("HTC", "HTC U11", "T-Mobile"),
("HTC", "HTC 12", "Verizon");

INSERT INTO Customer (firstName, lastName, username, passkey, salt) VALUES
("Saahil", "Kumar", "saahilkumar00", "$2b$10$7.MLCRFPhglI5tMqQq8lPecWRW5x7CCBZuRBLwr5FxrS2vt8Ful7O", "$2b$10$7.M"),
("David", "Yan", "yandapanda123", "$2b$10$.kOpovxWOzr.6w2F3OCLF.sD3BOU4ESi620GE525/sHcqNS1bF2Ei", "$2b$10$.kO"),
("Cheng Xi", "Tsou", "twitch_main3", "$2b$10$$2b$10$SprEzYfbuXxEYLpXDAm5COvnishNG4pPA1iT4Doho517X3l3HRPvO", "$2b$10$Spr"),
("Ningyu", "Chen", "ningyuning2", "$2b$10$Vca6ZGnJl.RSIIYhZd9us.H9L011FZ0pAAGygvW48DJhjclEQdAAa", "$2b$10$Vca"),
("Stanley", "Wu", "animelove24", "$2b$10$1EyE91Y4WxUNqBYl8CFqTek06u0/O/rCyqWElF1eNFJrOZCtdiV4W", "$2b$10$1Ey"),
("Anthony", "Mu", "mu.anthony2", "$2b$10$qL7PSqLumDlyjo/vmmXIGuYAIxNccT9/JVY5EdBK.Jxqc9GzrZynO", "$2b$10$qL7"),
("Patrick", "Yoon", "chicagoYoon20", "$2b$10$KmR8mIvlDVqsuq9fBSMXSe/Zpt.h8KVTCHWelOmCQYJVforoj1i9a", "$2b$10$KmR"),
("Vevey", "Zhan", "vv.zhan2", "$2b$10$PX3GNBunb363Wz/38aXaM.ENEwuLrmJGY/QDIHC3AhUR2CHIN8nPe", "$2b$10$PX3"),
("Shawn", "Spencer", "psychic1234", "$2b$10$hOVS.QucetjYLNf7OkrHhut2KKdqSRsI5ihds.DTQo2hvOKEYdoxm", "$2b$10$hOV"),
("Burton", "Guster", "pluto_lover6", "$2b$10$lyBEcfcg4ptUKHLuKwL9s.0q18zz8ESgDr8dGhJudLBY0k5Q2.y06", "$2b$10$lyB");

INSERT INTO Orders (orderNum, customerUsername) VALUES
(1, "saahilkumar00"),
(2, "saahilkumar00"),
(3, "saahilkumar00"),
(1, "yandapanda123"),
(2, "yandapanda123"),
(1, "twitch_main3"),
(2, "twitch_main3"),
(3, "twitch_main3"),
(4, "twitch_main3"),
(1, "animelove24"),
(1, "mu.anthony2"),
(1, "chicagoYoon20"),
(2, "chicagoYoon20"),
(3, "chicagoYoon20"),
(1, "vv.zhan2"),
(2, "vv.zhan2"),
(1, "psychic1234"),
(2, "psychic1234"),
(3, "psychic1234"),
(1, "pluto_lover6");

INSERT INTO OnlineOrder (orderNum, customerUsername, state, ofZip, ofCity, ofState, ofStreet) VALUES
(1, "mu.anthony2", "sent", "32281", "Madison", "Wisconsin", "123 Main Street"),
(1, "chicagoYoon20", "sent", "90293", "Boston", "Massachusetts", "17 Mouse Road"),
(2, "chicagoYoon20", "sent", "39021", "Boise", "Idaho", "1 Potato Lane"),
(3, "chicagoYoon20", "processed", "12314", "Springfield", "Illinois", "25 Simpson Grove"),
(1, "vv.zhan2", "processed", "02115", "Boston", "Massachusetts", "40 Leon Street"),
(2, "vv.zhan2", "processed", "13474", "Seattle", "Washington", "1234 Rainy Avenue"),
(1, "psychic1234", "delivered", "02115", "Boston", "Massachusetts", "129 Hemenway Street"),
(2, "psychic1234", "delivered", "99999", "Olympia", "Washington", "402 Fake Road"),
(3, "psychic1234", "lost", "00000", "Chicago", "Illinois", "12 PogChamp Road"),
(1, "pluto_lover6", "lost", "29172", "Ever Grande", "Hawaii", "12 Victory Road");


INSERT INTO Employee (firstName, lastName, title, reportTo, username, passkey, salt) VALUES
("Nate", "Derbinsky", "CEO", NULL, "ceoDerbinsky", "mouseAndKeyboard", "12"),
("Jayne", "Dwonson", "COO", "ceoDerbinsky", "cooDwonson", "titangames<3", "5d"),
("Hevin", "Kart", "CTO", "ceoDerbinsky", "ctoKart", "jumanji", "dk"),
("Melissa", "Tree", "CFO", "ceoDerbinsky", "cfoTree", "gardening4", "dl"),
("Samir", "Kumar", "Technology Manager", "ctoKart", "samkumar630", "fork_and_knife", "0A"),
("Jane", "Doe", "Software Developer", "samkumar630", "jDoe153", "softwareDev:)", "7d"),
("John", "Smith", "QA Analyst", "samkumar630", "jSmith018", "qaAnalyst:(", "Db"),
("Rodney", "Fisher", "HR Representative", "cooDwonson", "rFisher", "fishinLover", "dd"),
("Bill", "Bob", "Financial Manager", "cfoTree", "bbill", "moneymanager", "lE"),
("Bubba", "Kumar", "Salesman", "bbill", "bubba_sales", "lovesSqueakyToys", "pq"),
("Tyler", "Blevins", "Janitor", "rFisher", "tyBlevins", "janitor4lyfe", "nY"),
("Clare", "Crawley", "Hiring Manager", "rFisher", "clareC", "dale_moss", "q3"),
("Gordo", "Foodsey", "Chef", "rFisher", "gordofoodsey", "yukihirasoma", "0U"),
("Peter", "Pilot", "Consulting Intern", "clareC", "pPilot", "bbBachelorbb", "Pl"),
("Tony", "Shark", "Data Analyst Co-op", "jDoe153", "tonySh", "sokovia_accords", "lk"),
("Naruto", "Uzumaki", "Food Manager", "rFisher", "nUzu123", "shippuden", "e4"),
("Lucina", "Kumar", "Electrical Engineer", "bubba_sales", "lucinaK52", "huskyy.lucina", "95"),
("Giles", "Corey", "Stonemason", "clareC", "gCoreyToS", "mafclaimingvig", "rC"),
("Abby", "Yu", "Quality Manager", "ceoDerbinsky", "yu.abigail", "yugotaproblem", "pz"),
("James", "Pond", "Gardener", "rFisher", "jPond007", "skyfall.adele", "LQ");

INSERT INTO Store (state, city, zip, manager) VALUES
("Oregon", "Portland", "17233", "ceoDerbinsky"),
("Washington", "Seattle", "12921", "cooDwonson"),
("California", "San Francisco", "23712", "ctoKart"),
("Massachusetts", "Boston", "02115", "cfoTree"),
("Connecticut", "Hartford", "17232", "samkumar630"),
("California", "Los Angeles", "28102", "jDoe153"),
("Illinois", "Chicago", "11242", "jSmith018"),
("Alabama", "Alabama City", "99921", "rFisher"),
("Florida", "Tallahassee", "12734", "bbill"),
("Ohio", "Cleveland", "12812", "bubba_sales"),
("Pennsylvania", "Pittsburgh", "72942", "tyBlevins"),
("Nevada", "Las Vegas", "12803", "clareC"),
("North Dakota", "Fargo", "73943", "gordofoodsey"),
("Alaska", "Juneau", "28192", "pPilot"),
("North Carolina", "Raleigh", "24932", "tonySh"),
("Hawaii", "Honolulu", "01238", "nUzu123"),
("New York", "Albany", "74923", "lucinaK52"),
("Wisconsin", "Madison", "02384", "gCoreyToS"),
("Pennsylvania", "Philadelphia", "73102", "yu.abigail"),
("Maine", "Ogunquit", "92384", "jPond007");


INSERT INTO OnlineStore (url, ofState, ofCity, ofZip) VALUES
("http://www.huskytech.com/portland", "Oregon", "Portland", "17233"),
("http://www.huskytech.com/seattle", "Washington", "Seattle", "12921"),
("http://www.huskytech.com/california", "California", "San Francisco", "23712"),
("http://www.huskytech.com/boston", "Massachusetts", "Boston", "02115"),
("http://www.huskytech.com/hartford", "Connecticut", "Hartford", "17232"),
("http://www.huskytech.com/la", "California", "Los Angeles", "28102"),
("http://www.huskytech.com/chicago", "Illinois", "Chicago", "11242"),
("http://www.huskytech.com/alabamacity", "Alabama", "Alabama City", "99921"),
("http://www.huskytech.com/tallahassee", "Florida", "Tallahassee", "12734"),
("http://www.huskytech.com/cleveland", "Ohio", "Cleveland", "12812");

INSERT INTO WorksAt (employeeUsername, ofState, ofCity, ofZip) VALUES
("cfoTree", "California", "Los Angeles", "28102"),
("tyBlevins", "Illinois", "Chicago", "11242"),
("bbill", "Alabama", "Alabama City", "99921"),
("ctoKart", "Alabama", "Alabama City", "99921"),
("cooDwonson", "Alabama", "Alabama City", "99921"),
("gordofoodsey", "Florida", "Tallahassee", "12734"),
("tyBlevins", "Ohio", "Cleveland", "12812"),
("cfoTree", "Ohio", "Cleveland", "12812"),
("lucinaK52", "Pennsylvania", "Pittsburgh", "72942"),
("clareC", "Pennsylvania", "Pittsburgh", "72942"),
("samkumar630", "Pennsylvania", "Pittsburgh", "72942"),
("bubba_sales", "Nevada", "Las Vegas", "12803"),
("ceoDerbinsky", "North Dakota", "Fargo", "73943"),
("jDoe153", "North Dakota", "Fargo", "73943"),
("gCoreyToS", "Alaska", "Juneau", "28192"),
("jPond007", "Alaska", "Juneau", "28192"),
("lucinaK52", "North Carolina", "Raleigh", "24932");


INSERT INTO Review (brandType, modelType, customerUsername, rating, descr) VALUES
("Dell", "XPS 15", "saahilkumar00", 10, "Amazing product! Loved it a lot and it worked very well"),
("Dell", "XPS 13", "yandapanda123", 7, "Works pretty well, I noticed a bug though whenever I try to open a web browser."),
("Apple", "MacBook Air", "saahilkumar00", 8, "Really easy to use and great price! I wish it was a little bigger however."),
("Apple", "MacBook Air", "yandapanda123", 4, "A lot of people seem to like this product but not me. It’s hard to use and too small"),
("Apple", "MacBook Air", "twitch_main3", 10, "This is the best laptop that I’ve ever used!"),
("Apple", "MacBook Pro", "yandapanda123", 4, "Not nearly as good as other laptops, it’s way too expensive and super slow."),
("Google", "Pixelbook Go", "twitch_main3", 2, "Sorry I thought I was getting Pokemon Go for my grandson can I get a refund?"),
("Lenovo", "X1 Carbon Gen 8", "saahilkumar00", 5, "Works well but it’s very expensive, so not totally worth the price in my opinion."),
("Lenovo", "X1 Carbon Gen 8", "yandapanda123", 7, "Kind of expensive but definitely worth it."),
("Lenovo", "X1 Carbon Gen 7", "ningyuning2", 1, "This is probably the worst product I’ve ever used."),
("Alienware", "Alienware m15 R3", "ningyuning2", 3, "It’s good but not when you compare it to its competitors. Honestly, they really need to pick up their game."),
("Apple", "IPhone X", "yandapanda123", 10, "Amazing phone and great price! It’s fun to use and my kids love it."),
("Apple", "IPhone 11", "animelove24", 8, "This is a really great phone but it’s a little expensive, especially considering it’s not too different from the IPhone X"),
("Apple", "IPhone 11", "saahilkumar00", 6, "The camera quality is not very good, which is unfortunate since it has three of them."),
("Apple", "IPhone 11", "yandapanda123", 7, "Pretty good phone, the apps are the best part to be honest."),
("Apple", "IPhone 11", "chicagoYoon20", 9, "Best phone I’ve ever seen." ),
("Apple", "IPhone 8", "ningyuning2", 1, "Would not even buy it for my dog."),
("Apple", "IPhone 8", "animelove24", 4, "The camera quality could be better."),
("Samsung", "Galaxy Note 7", "yandapanda123", 1, "Had to call 911 after the phone exploded, never buy this product."),  
("Google", "Google Pixel 5", "saahilkumar00", 2, "I love Google but this phone is honestly terrible."),
("Google", "Google Pixel 4", "ningyuning2", 6, "Better than Google’s other phones but it’s still a little too expensive."),
("Google", "Google Pixel 4", "animelove24", 8, "This is the best Google phone by far. Hands down."),
("Google", "Google Pixel 4", "chicagoYoon20", 7, "Great phone! There’s room for improvement but it’s still good."),
("Nokia", "Nokia 3V", "chicagoYoon20", 1, "Terrible quality, the only nokia i managed to break."),
("HTC", "HTC U11", "ningyuning2", 9, "I love the three lense camera and the new home button feature!"),
("HTC", "HTC 12", "yandapanda123", 6, "Not as good as some of HTC’s other products but I still use it a lot."),
("Dell", "Inspiron 24 5000", "vv.zhan2", 3, "I regret using Dell for anything other than printers"),
("Dell", "Inspiron 24 5000", "saahilkumar00", 5, "It’s not bad, but it’s not very good either. I wouldn’t recommend buying it."),
("Dell", "Inspiron 24 5000", "animelove24", 4, "It’s super slow and hard to use. Dell really needs to get their act together."),
("Dell", "Inspiron 27 7000", "yandapanda123", 6, "The computer lags at times but can still run most applications easily."),
("Lenovo", "IdeaCentre A540", "ningyuning2", 7, "Decent, but not great."),
("Lenovo", "IdeaCentre A540", "chicagoYoon20", 10, "Crazy fast CPU and insane GPU, this is the best product I’ve ever used."),
("Lenovo", "Yoga A940", "vv.zhan2", 10, "Using this makes me want to go and do yoga."),
("Microsoft", "Surface Studio 2", "ningyuning2", 10, "It’s exactly the good quality that you’d expect from Microsoft"),
("Microsoft", "Surface Studio 2", "saahilkumar00", 1, "Thisissobadthespacedoesntevenwork"),
("Microsoft", "Surface Studio 2", "yandapanda123", 5, "The keys are super sticky which is annoying but it’s a good product overall"),
("Apple", "iMac", "mu.anthony2", 5, "It’s good, but there are some issues that make it bothersome to use sometimes."),
("Apple", "Mac mini", "yandapanda123", 5, "Not the best apple product but not the worst either."),
("Apple", "Mac mini", "ningyuning2", 1, "Why is it so mini?? This product is terrible."),
("Apple", "Mac mini", "mu.anthony2", 4, "This product’s decent but there’s lots of room for improvement"),
("Apple", "Mac mini", "vv.zhan2", 5, "It’s good but not nearly as good as any of the other Apple products."),
("HP", "HP Z2 Mini G4", "mu.anthony2", 1, "I’ve never even heard of HP before using this desktop but now I know why it’s a no name brand");


INSERT INTO Merchandise(serial, brandType, modelType, shelfState, shelfCity, shelfZIP, orderID, customerUsername) VALUES
("#73917", "Dell", "XPS 15", "Oregon", "Portland", "17233", NULL, NULL),
("#37923", "Dell", "XPS 15", "Oregon", "Portland", "17233", NULL, NULL),
("#79212", "Dell", "XPS 15", "Washington", "Seattle", "12921", 1, "pluto_lover6"),
("#12309", "Dell", "XPS 15", "North Dakota", "Fargo", "73943", NULL, NULL),
("#64923", "Dell", "XPS 13", "California", "San Francisco", "23712", NULL, NULL),
("#12057", "Dell", "XPS 13", "Oregon", "Portland", "17233", 3, "psychic1234"),
("#15351", "Apple", "MacBook Air", "Washington", "Seattle", "12921", 2, "psychic1234"),
("#75923", "Apple", "MacBook Air", "Oregon", "Portland", "17233", 2, "psychic1234"),
("#03471", "Apple", "MacBook Air", "Oregon", "Portland", "17233", 1, "psychic1234"),
("#93724", "Apple", "MacBook Pro", "Alaska", "Juneau", "28192", 1, "psychic1234"),
("#78346", "Apple", "MacBook Pro", "California", "San Francisco", "23712", 1, "psychic1234"),
("#62347", "Samsung", "Galaxy Book", "Washington", "Seattle", "12921", 1, "saahilkumar00"),
("#00239", "Google", "Pixelbook Go", "California", "San Francisco", "23712", 1, "saahilkumar00"),
("#42348", "Lenovo", "X1 Carbon Gen 8", "Alaska", "Juneau", "28192", 1, "saahilkumar00"),
("#72349", "Lenovo", "X1 Carbon Gen 8", "Oregon", "Portland", "17233", NULL, NULL),
("#62348", "Lenovo", "X1 Carbon Gen 8", "Washington", "Seattle", "12921", NULL, NULL),
("#68234", "Lenovo", "X1 Carbon Gen 8", "California", "San Francisco", "23712", 2, "vv.zhan2"),
("#92834", "Lenovo", "X1 Carbon Gen 7", "Alaska", "Juneau", "28192", 2, "saahilkumar00"),
("#23493", "Alienware", "Alienware m15 R3", "Washington", "Seattle", "12921", 2, "saahilkumar00"),
("#12834", "Alienware", "Alienware m15 R3", "Oregon", "Portland", "17233", 2, "saahilkumar00"),
("#99912", "Alienware", "Alienware Area-51m r2", "New York", "Albany", "74923", 1, "vv.zhan2"),
("#62844", "Alienware", "Alienware Area-51m r2", "New York", "Albany", "74923", 1, "vv.zhan2"),
("#12353", "Alienware", "Alienware Area-51m r2", "Pennsylvania", "Philadelphia", "73102", 1, "vv.zhan2"),
("#48234", "Apple", "IPhone X", "Massachusetts", "Boston", "02115", NULL, NULL),
("#73532", "Apple", "IPhone X", "Oregon", "Portland", "17233", 3, "saahilkumar00"),
("#01283", "Apple", "IPhone X", "North Carolina", "Raleigh", "24932", 3, "saahilkumar00"),
("#01232", "Apple", "IPhone 11", "Washington", "Seattle", "12921", NULL, NULL),
("#82348", "Apple", "IPhone 11", "New York", "Albany", "74923", 3, "chicagoYoon20"),
("#01239", "Apple", "IPhone 11", "Washington", "Seattle", "12921", 3, "chicagoYoon20"),
("#12352", "Apple", "IPhone 11", "Ohio", "Cleveland", "12812", 2, "chicagoYoon20"),
("#18423", "Apple", "IPhone 11", "Ohio", "Cleveland", "12812", 2, "chicagoYoon20"),
("#12948", "Apple", "IPhone 8", "North Carolina", "Raleigh", "24932", 2, "chicagoYoon20"),
("#38347", "Samsung", "Galaxy Note 7", "Washington", "Seattle", "12921", NULL, NULL),  
("#71239", "Google", "Google Pixel 5", "Massachusetts", "Boston", "02115", NULL, NULL),
("#09123", "Google", "Google Pixel 5", "Massachusetts", "Boston", "02115", NULL, NULL),
("#47832", "Google", "Google Pixel 5", "Florida", "Tallahassee", "12734", 1, "chicagoYoon20"),
("#45734", "Google", "Google Pixel 4", "Washington", "Seattle", "12921", 1, "chicagoYoon20"),
("#98982", "Nokia", "Nokia 3V", "Florida", "Tallahassee", "12734", 1, "yandapanda123"),
("#23532", "Nokia", "Nokia 6.2", "North Dakota", "Fargo", "73943", 1, "mu.anthony2"),
("#98298", "HTC", "HTC U11", "Washington", "Seattle", "12921", 1, "mu.anthony2"),
("#93728", "HTC", "HTC 12", "Massachusetts", "Boston", "02115", NULL, NULL),
("#09091", "HTC", "HTC 12", "Florida", "Tallahassee", "12734", 2, "yandapanda123"),
("#98912", "HTC", "HTC 12", "Wisconsin", "Madison", "02384", 1, "twitch_main3"),
("#44457", "Dell", "Inspiron 24 5000", "Washington", "Seattle", "12921", 1, "twitch_main3"),
("#90123", "Dell", "Inspiron 24 5000", "Maine", "Ogunquit", "92384", 1, "twitch_main3"),
("#78934", "Dell", "Inspiron 27 7000", "Hawaii", "Honolulu", "01238", NULL, NULL),
("#12087", "Dell", "OptiPlex 7780", "Hawaii", "Honolulu", "01238", NULL, NULL),
("#02764", "Lenovo", "IdeaCentre A540", "Maine", "Ogunquit", "92384", 3, "twitch_main3"),
("#49398", "Lenovo", "Yoga A940", "California", "Los Angeles", "28102", 3, "twitch_main3"),
("#44758", "Microsoft", "Surface Studio 2", "Washington", "Seattle", "12921", 3, "twitch_main3"),
("#33231", "Microsoft", "Surface Studio 2", "Massachusetts", "Boston", "02115", NULL, NULL),
("#54738", "Microsoft", "Surface Studio 2", "California", "Los Angeles", "28102", NULL, NULL),
("#01284", "Microsoft", "Surface Studio 2", "Connecticut", "Hartford", "17232", 3, "twitch_main3"),
("#47829", "Apple", "iMac", "Wisconsin", "Madison", "02384", 2, "twitch_main3"),
("#64949", "Apple", "iMac", "Wisconsin", "Madison", "02384", 2, "twitch_main3"),
("#63847", "Apple", "Mac mini", "Massachusetts", "Boston", "02115", 2, "twitch_main3"),
("#73827", "HP", "HP EliteOne 800", "Washington", "Seattle", "12921", 1, "mu.anthony2"),
("#09124", "HP", "HP Z2 Mini G4", "Connecticut", "Hartford", "17232", 1, "mu.anthony2");
